name = "lead-fountain-bot"
main = "lead_fountain.py"
compatibility_date = "2024-03-18"

# THIS LINE IS CRITICAL:
compatibility_flags = ["python_workers", "python_v2"]

[[kv_namespaces]]
binding = "LEAD_HISTORY"
id = "1c5cb82a3085400dbc218c91a73446a1"
