name = "lead-fountain-bot"
main = "index.py"  # <--- Change this to index.py
compatibility_date = "2026-02-05"
compatibility_flags = ["python_workers"]

[[kv_namespaces]]
binding = "LEAD_HISTORY"
id = "1c5cb82a3085400dbc218c91a73446a1"
